apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  selector:
    matchLabels:
      app: cicd-project
  replicas: 2

  template:
    metadata:
      labels:
        app: cicd-project
    spec:
      containers:
      - name: cicd-project
        image: salgu1998/cicd-project
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
