apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: snackbar
  labels:
    service: payment
    project: snackbar

spec:
  type: ClusterIP
  selector:
    service: payment
    project: snackbar
  ports:
    - port: 80
      targetPort: 8080