apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: snackbar
  labels:
    service: order
    project: snackbar

spec:
  type: ClusterIP
  selector:
    service: order
    project: snackbar
  ports:
  - port: 80
    targetPort: 8080