apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: snackbar
  labels:
    service: order
    project: snackbar

spec:
  type: LoadBalancer
  selector:
    service: order
    project: snackbar
  ports:
  - port: 80
    targetPort: 8080

#  kubectl apply -f loadbalancer/order-service-loadbalancer.yml
#  kubectl apply -f loadbalancer/payment-service.yml
#  kubectl apply -f loadbalancer/order-deployment.yml
#  kubectl apply -f loadbalancer/payment-deployment.yml