apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: core
  labels:
    app: payment

spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - port: 18080
      targetPort: 18080