apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: core
  labels:
    app: ingress

spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /auth
        backend:
          service:
            name: auth
            namespace: auth
            port:
              number: 18080

      - pathType: Prefix
        path: /api
        backend:
          service:
            name: api
            namespace: api
            port:
              number: 18080