apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}

spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}

  template:
    metadata:
      labels:
        app: {{.Values.name}}

    spec:
      containers:
      - name: {{.Values.name}}
        image: salgu-{{.Values.name}}:{{.Values.version}}
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 18080
        env:
        - name: PROFILE
          value: {{.Values.profiles}}
        - name: API_URL
          value: api.core.svc.cluster.local:18080

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}

spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - port: 18080
      targetPort: 18080