kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-allow-auth
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.name}}
  ingress:
  - ports:
    - port: {{.Values.containerPort}}
    from:
    {{- toYaml .Values.networkPolicy.fromPodLabels | nindent 4 }}