apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-{{.Release.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
  annotations:
    kubernetes.io/change-cause: {{.Values.changeCause}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: salgu-{{.Values.name}}:{{.Values.version}}
        resources:
          limits:
            memory: {{.Values.memory}}
            cpu: {{.Values.cpu}}
        ports:
        - containerPort: {{.Values.containerPort}}
        env:
        - name: PROFILE
          valueFrom:
            configMapKeyRef:
              name: profiles
              key: profiles
        - name: VERSION
          value: {{.Values.version}}
#        - name: DB_URL
#          value: 192.168.35.187
        livenessProbe:
          httpGet:
            path: /status
            port: 18080
          initialDelaySeconds: 60 # 컨테이너 시작 후 몇초 후에 probe를 시작할 것인가
          periodSeconds: 10        # probe 실행 주기
          successThreshold: 1     # 몇개 성공 시 실패 횟수를 초기화할 것인가
          failureThreshold: 3     # 연속으로 몇번 실패 했을때 컨테이너를 재시작할 것인가
          timeoutSeconds: 5       # 응답을 몇초만에 받아야 하는가
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1