apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: core
  labels:
    app: {{.Values.name}}

spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}